-- Import Lehrerliste in makerspace.werkstattbenutzer
-- Passwort fuer alle importierten Lehrer: InitPass2026! (bitte danach aendern)
START TRANSACTION;
ALTER TABLE werkstattbenutzer ADD COLUMN Titel VARCHAR(50) NULL AFTER Nachname;
ALTER TABLE werkstattbenutzer ADD COLUMN Email VARCHAR(255) NULL AFTER Username;
ALTER TABLE werkstattbenutzer ADD UNIQUE KEY uq_werkstattbenutzer_email (Email);
ALTER TABLE werkstattbenutzer ADD UNIQUE KEY uq_werkstattbenutzer_username (Username);

INSERT IGNORE INTO werkstattbenutzer (Vorname, Nachname, Titel, Username, Email, Passwort, Rolle, Klasse)
VALUES
  ('Heike', 'ABART', 'Mag.', 'habart', 'heike.abart@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Michaela', 'AICHNER', 'Mag.', 'maichner', 'michaela.aichner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Philipp', 'AMBROSI', 'Ing. BSc, MSc', 'pambrosi', 'philipp.ambrosi@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Markus', 'AMANN', 'DI (FH)', 'mamann', 'markus.amann@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andrea', 'AUER', 'Mag.', 'aauer', 'andrea.auer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Nora', 'BARBIST', 'Mag.', 'nbarbist', 'nora.barbist@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Clemens', 'BAUMANN', 'Ing. BEd', 'cbaumann', 'clemens.baumann@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Manuel', 'BERGERWEIß', 'AV BEd., Ing. B.Sc., M.Sc.', 'mbergerweiss', 'manuel.bergerweiss@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Klaus', 'BICHLER', 'Ing. Dipl.-Ing.(FH)', 'kbichler', 'klaus.bichler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Gerhard', 'BRANDACHER', 'Dipl.-Päd.', 'gbrandacher', 'gerhard.brandacher@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Johannes', 'BUCHER', 'Mag. Dr.', 'jbucher', 'johannes.bucher@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Martin', 'CECH', 'Ing. Dipl.-Päd.', 'mcech', 'martin.cech@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Katarina', 'DANZL', 'Bsc. Msc. Dr.', 'kdanzl', 'katarina.danzl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Matthias', 'DAXER', 'Mag.', 'mdaxer', 'matthias.daxer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Herwig Franz', 'DREXEL', 'Mag. Dr.', 'hdrexel', 'herwig.drexel@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Josef', 'DUMMER', 'Ing.', 'jdummer', 'josef.dummer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Franz', 'ECCHER', 'Mag.', 'feccher', 'franz.eccher@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andreas', 'ECKHART', 'Ing. BEd. MSc.', 'aeckhart', 'andreas.eckhart@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Philipp', 'EIBL', 'Ing. BSc. MSc.', 'peibl', 'philipp.eibl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Johannes', 'ELLER', 'Mag.', 'jeller', 'johannes.eller@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andreas', 'ELLER', 'FL', 'aeller', 'andreas.eller@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Jakob', 'ERLER', 'Ing. Dipl.-Päd. BEd', 'jerler', 'jakob.erler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Cornelia', 'FALCH', 'Dr.', 'cfalch', 'cornelia.falch@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Rudolf', 'FALLMANN', 'DDr. MSc', 'rfallmann', 'rudolf.fallmann@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Stefan', 'FANKHAUSER', 'Ing. Dipl.-Päd. BEd', 'sfankhauser', 'stefan.fankhauser@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Anton', 'FEURSTEIN', 'Mag.', 'afeurstein', 'anton.feurstein@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Benedikt', 'FRISCHMANN', 'Dipl.-Ing.', 'bfrischmann', 'benedikt.frischmann@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Günther', 'GÄNSLUCKNER', 'Mag.', 'ggaensluckner', 'guenther.gaensluckner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Rene', 'GERSTGRASSER', NULL, 'rgerstgrasser', 'rene.gerstgrasser@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Leopold', 'GÖTSCH', 'DI', 'lgoetsch', 'leopold.goetsch@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Helmut', 'GRAGGER', 'Ing. Dipl.-Päd. BEd.', 'hgragger', 'helmut.gragger@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Albert', 'GREINÖCKER', 'Mag. Dr. DI', 'agreinoecker', 'albert.greinoecker@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Katharina', 'GRIF', 'DI Dr.', 'kgrif', 'katharina.grif@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Michael', 'GRIF', 'DI', 'mgrif', 'michael.grif@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Engelbert', 'GRUBER', 'VL.', 'egruber', 'engelbert.gruber@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andrea', 'GUTHEINZ-NAGILLER', 'Mag.', 'agutheinznagiller', 'andrea.gutheinz-nagiller@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Karin', 'HAAS', 'MMag.', 'khaas', 'karin.haas@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Wolfgang', 'HACKL', 'Ing. Dipl.-Ing. (FH)', 'whackl', 'wolfgang.hackl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Stephanie', 'HAGER-RUDIG', 'MMag.', 'shagerrudig', 'stephanie.hager-rudig@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Birgit', 'HANAK-ELLER', 'Mag.', 'bhanakeller', 'birgit.hanak-eller@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Ines', 'HAUBOLD', 'Dipl.-Ing.in', 'ihaubold', 'ines.haubold@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Christian', 'HILPOLD', 'Ing. Dipl.-Päd. BEd', 'chilpold', 'christian.hilpold@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Karin', 'HIRSCH', 'Mag.', 'khirsch', 'karin.hirsch@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Gernot', 'HOCHENWARTER', 'Dipl.-Ing.', 'ghochenwarter', 'gernot.hochenwarter@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Thomas', 'HOFER', 'Ing. BEd', 'thofer', 'thomas.hofer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Herbert', 'HOLAUS', 'Dipl.-Päd., Dipl.-Ing.(FH)', 'hholaus', 'herbert.holaus@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andreas', 'HOLZMANN', 'Dipl.-Ing.', 'aholzmann', 'andreas.holzman@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Martin', 'HUBER', 'Mag. Dr.', 'mhuber', 'martin.huber@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Johannes', 'HUTER', 'Mag.', 'jhuter', 'johannes.huter@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Alexander', 'JAMBOR', 'MMag.', 'ajambor', 's.jambor@tsn.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andreas', 'JANK', 'Mag.', 'ajank', 'andreas.jank@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Alexander', 'JÄGER', 'Mag.', 'ajaeger', 'alexander.jaeger@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Stefan', 'JUEN', 'Mag. Dr. BSc', 'sjuen', 'stef.juen@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Stefan', 'JUEN', 'Mag.', 'sjuen2', 'stefan.juen@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Dominic', 'JULI', 'BEd', 'djuli', 'dominic.juli@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Claudia', 'JUNGL', 'Mag.', 'cjungl', 'claudia.jungl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Mario', 'JUNKER', 'MMMag., MSc', 'mjunker', 'mario.junker@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Okan', 'KANSIZ', 'Dpäd.Mmag.Bed.', 'okansiz', 'o.kansiz@tsn.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Alexander', 'KAISER', 'Dipl.-Ing., PHD, BEd, MEd', 'akaiser', 'alexander.kaiser@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Roland', 'KASINGER', 'Ing.', 'rkasinger', 'roland.kasinger@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Johannes', 'KECKEIS', 'Mag.', 'jkeckeis', 'johannes.keckeis@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Roland', 'KIENAST', 'Ing. Dipl.-Ing. Dr. Bakk.', 'rkienast', 'roland.kienast@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Felix', 'KLINGLER', 'Mag.(FH) Dipl.-Ing.', 'fklingler', 'felix.klingler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Hannes', 'KLOTZ', 'DI (FH), MSc, BEd.', 'hklotz', 'hannes.klotz@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Jörg', 'KNOFLER', 'AV Dipl.-Ing.', 'jknofler', 'joerg.knofler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Patrick', 'KORBER', 'Mag. MEd. MSc. BEd.', 'pkorber', 'patrick.korber@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Christoph', 'KÖHLE', 'AV Ing. Dipl.-Päd. Dipl.-Ing. (FH)', 'ckoehle', 'christoph.koehle@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Christof', 'KUEN', 'Ing.', 'ckuen', 'christof.kuen@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Michael', 'KUPFNER', 'DI. DI.', 'mkupfner', 'michael.kupfner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Simon', 'KUTTNER', 'Mag.', 'skuttner', 'simon.kuttner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Daniel', 'LAIR', 'Ing. BEd.', 'dlair', 'daniel.lair@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Simon', 'LAMPRECHT', 'Ing.', 'slamprecht', 'simon.lamprecht@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Martin', 'LARCHER', 'Dipl.-Päd. BEd. Ing.', 'mlarcher', 'martin.larcher@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Wolfram', 'LASSNIG', 'Ing. Dipl.-Päd. BEd', 'wlassnig', 'wolfram.lassnig@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Alexander', 'LECHNER', NULL, 'alechner', 'alexander.lechner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Jürgen', 'LINTNER', 'Ing. Dipl.-Päd. BEd', 'jlintner', 'juergen.lintner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Michael', 'LOINGER', 'Dipl.-Ing.', 'mloinger', 'michael.loinger@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Gerhard', 'LUCHNER', 'Ing. Dipl.-Päd. BEd', 'gluchner', 'gerhard.luchner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Elsbeth', 'LUKASSER', 'Mag.', 'elukasser', 'elsbeth.lukasser@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Werner', 'MAIR', 'Dipl.-Ing.', 'wmair', 'werner.mair@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Lisa', 'MANZL', 'Mag.', 'lmanzl', 'lisa.manzl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Sylvia', 'MAYR', 'Mag.', 'smayr', 'sylvia.mayr@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Johannes', 'MAYR', 'Ing. Mag.', 'jmayr', 'johannes.mayr@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Armin', 'MOSER', 'Mag.', 'amoser', 'armin.moser@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Walter', 'MUELLER', 'Mag.', 'wmueller', 'walter.mueller@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Sarah', 'NEPO', 'Mag.', 'snepo', 'sarah.nepo@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Thomas', 'NETZER', 'Ing. Dipl.-Ing. (FH) Dipl.-Päd. BEd', 'tnetzer', 'thomas.netzer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Martin', 'NEUHAUSER', 'Dipl.-Ing.', 'mneuhauser', 'martin.neuhauser@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Peter', 'NOWAK-RAINER', 'Mag.', 'pnowakrainer', 'peter.nowak@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Stefan', 'OBERPRANTACHER-ZIMMERMANN', 'Ing. Dipl.-Päd. BEd.', 'soberprantacherzimmermann', 'stefan.oberprantacher@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Florian', 'OEHLINGER', 'BSc, MSc, BEd', 'foehlinger', 'florian.oehlinger@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Roland', 'OHNMACHT', 'Dipl.-Ing.(FH)', 'rohnmacht', 'roland.ohnmacht@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Bernhard', 'OSTHEIMER', 'Ing. BEd.', 'bostheimer', 'bernhard.ostheimer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andreas', 'PANWINKLER', NULL, 'apanwinkler', 'andreas.panwinkler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Emanuel', 'PATER', NULL, 'epater', 'emanuel.dirlas@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Eva', 'PELLEGRINI', 'Mag.', 'epellegrini', 'eva.pellegrini@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Simon', 'PFANDLER', 'DI (FH)', 'spfandler', 'simon.pfandler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Johannes', 'PFATSCHBACHER', 'Dipl.-Ing. M.A.', 'jpfatschbacher', 'johannes.pfatschbacher@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Harald', 'PIOCK', 'Dipl.-Ing.', 'hpiock', 'harald.piock@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Alexander', 'PITTL', 'Mag.', 'apittl', 'alexander.pittl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Mario', 'PRANTL', 'DI (FH)', 'mprantl', 'mario.prantl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Thomas Bernhard', 'RABANSER', NULL, 'trabanser', 'thomas.rabanser@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Anna', 'PUNTAJER', 'Mag. Dr.', 'apuntajer', 'anna.puntajer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Matthias', 'REHEIS', 'MMag.', 'mreheis', 'matthias.reheis@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Hannelore', 'REICHMANN', 'Mag. Dr.', 'hreichmann', 'hannelore.reichmann@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andreas', 'REIMAIR', 'AV Mag.', 'areimair', 'andreas.reimair@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Elisabeth', 'REIMAIR', 'Mag. Dr.', 'ereimair', 'elisabeth.reimair@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Andrea', 'REITER', 'Mag. MA', 'areiter', 'andrea.reiter@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Monika', 'REITERER', 'Mag.', 'mreiterer', 'monika.reiterer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Johannes', 'RIEF', 'Dipl.-Ing.', 'jrief', 'johannes.rief@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Sabo', 'RUBNER', 'Bakk.', 'srubner', 'sabo.rubner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Klaus', 'RUETZ', 'Ing. BEd.', 'kruetz', 'klaus.ruetz@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Michael', 'RUETZ', 'Ing.', 'mruetz', 'michael.ruetz@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Katharina', 'SAILER', 'Mag.', 'ksailer', 'katharina.sailer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Richard', 'SANDBICHLER', 'Ing. Dipl.-Päd.', 'rsandbichler', 'richard.sandbichler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Jonas', 'SANNICOLO', 'Mag.', 'jsannicolo', 'jonas.sannicolo@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Katharina', 'SCHALLHART', 'MMag.', 'kschallhart', 'katharina.schallhart@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Kevin', 'SCHIECHTL', 'Dipl.-Ing.(FH)', 'kschiechtl', 'kevin.schiechtl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Johannes', 'SCHMID', 'DI (FH)', 'jschmid', 'johannes.schmid@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Martin', 'SCHÖPF', 'MSc.', 'mschoepf', 'martin.schoepf@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Otto', 'SCHULLERUS', 'Dipl.-Ing.', 'oschullerus', 'otto.schullerus@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Richard', 'SCHWANINGER', 'Dipl.-Ing.(FH), MSc.', 'rschwaninger', 'richard.schwaninger@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('David', 'SCHWARZL', 'Mag.', 'dschwarzl', 'david.schwarzl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Sabine', 'SEEWALD', 'M.A.', 'sseewald', 'sabine.seewald@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Werner', 'SEJKORA', 'Mag.', 'wsejkora', 'werner.sejkora@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Günther', 'SENFTER', 'Dipl.-Ing.', 'gsenfter', 'guenther.senfter@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Gilbert', 'SENN', 'MMag. Dr.', 'gsenn', 'gilbert.senn@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Markus', 'SIGNITZER', 'Ing. MSc', 'msignitzer', 'markus.signitzer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Lennart', 'SITAR', 'MSc', 'lsitar', 'lennart.sitar@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Toni', 'SPILDENNER', 'DI, M.A.', 'tspildenner', 'toni.spildenner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Regina', 'STANDÚN', 'Mag. Dr.', 'rstandn', 'regina.standun@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Helmut', 'STECHER', 'Ing. DI(FH) Dipl. Päd., BEd', 'hstecher', 'helmut.stecher@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Florian', 'STICHLBERGER', 'Ing.', 'fstichlberger', 'florian.stichlberger@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Daniel', 'STIX', 'Dipl.-Ing. BSc', 'dstix', 'daniel.stix@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Peter', 'STROHMAIER', 'Ing. Dipl.-Päd. BEd', 'pstrohmaier', 'peter.strohmaier@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Lukas', 'TAPPEINER', 'Dipl.-Ing. BSc.', 'ltappeiner', 'lukas.tappeiner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Stefan', 'THALER', 'Ing. BEd', 'sthaler', 'stefan.thaler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Uwe', 'THEURER', 'Dipl.-Ing.', 'utheurer', 'uwe.theurer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Norbert', 'THURNER', 'Dipl.-Ing.', 'nthurner', 'norbert.thurner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Reinhard', 'THURNER', 'Ing. Dipl.-Päd. BEd.', 'rthurner', 'reinhard.thurner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Siegfried', 'TRENKWALDER', 'Dipl.-Ing. (FH), BEd.', 'strenkwalder', 'siegfried.trenkwalder@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Adem', 'UGUR', 'MA', 'augur', 'adem.ugur@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Eva', 'UNTERRADER', 'Mag.', 'eunterrader', 'eva.unterrader@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Hans', 'VOGT', 'Mag.', 'hvogt', 'hans.vogt@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Thomas', 'WAIBL', 'Dipl.-Ing.', 'twaibl', 'thomas.waibl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Birgit', 'WALCH', 'Mag. Dipl.-Ing.in', 'bwalch', 'birgit.walch@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Martin', 'WALLNÖFER', 'Ing. BEd', 'mwallnoefer', 'martin.wallnoefer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Erich', 'WALTER', 'M.A. Mag. Dipl.-Ing. OStR.', 'ewalter', 'erich.walter@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Stefan', 'WECHNER', 'DI', 'swechner', 'stefan.wechner@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Thomas', 'WEILER', 'Mag.', 'tweiler', 'thomas.weiler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Nikolaus', 'WEITHAS', 'Mag.', 'nweithas', 'nikolaus.weithas@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Harald', 'WESENJAK', 'Dipl.-Ing.', 'hwesenjak', 'harald.wesenjak@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Armin', 'WICHT', 'B.Eng.', 'awicht', 'armin.wicht@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Edwin', 'WIEDENHOFER', 'Mag.', 'ewiedenhofer', 'edwin.wiedenhofer@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Natalie', 'WILHELM', 'Mag.', 'nwilhelm', 'natalie.wilhelm@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Philipp', 'WISCHOUNIG', 'Dipl.-Ing. Mag., BSc BSc', 'pwischounig', 'philipp.wischounig@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Ecem', 'YILDIRIM', NULL, 'eyildirim', 'ecem.yildirim@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Volkan', 'YANARDAG', 'DI', 'vyanardag', 'volkan.yanardag@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Wolfgang', 'ZANGERL', 'BEd.', 'wzangerl', 'wolfgang.zangerl@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL),
  ('Günther', 'ZIEGLER', 'Dipl.-Ing.', 'gziegler', 'guenther.ziegler@htlinn.ac.at', '$2y$10$XGcQVpPc/TeiH8/5cR2l1.bxJ5nqVZnKyRA1i32ZgHDJuabz879Tq', 'Lehrer', NULL);
COMMIT;